export const TYPES = {
    phpUnitXML: Symbol.for('PHPUnitXML'),
    printer: Symbol.for('Printer'),
    configuration: Symbol.for('Configuration'),
    testController: Symbol.for('TestController'),
    outputChannel: Symbol.for('OutputChannel'),
    testCollection: Symbol.for('TestCollection'),
    testRunnerFactory: Symbol.for('TestRunnerFactory'),
    handler: Symbol.for('Handler'),
    phpUnitLinkProvider: Symbol.for('PHPUnitLinkProvider'),
    testCommandRegistry: Symbol.for('TestCommandRegistry'),
    fileChangedEmitter: Symbol.for('FileChangedEmitter'),
    testFileDiscovery: Symbol.for('TestFileDiscovery'),
    testFileWatcher: Symbol.for('TestFileWatcher'),
    continuousTestRunner: Symbol.for('ContinuousTestRunner'),
    coverageCollector: Symbol.for('CoverageCollector'),
    testDiscovery: Symbol.for('TestDiscovery'),
    messageObserver: Symbol.for('MessageObserver'),
    outputChannelObserver: Symbol.for('OutputChannelObserver'),
};
