export const TYPES = {
    phpUnitXML: Symbol.for('PHPUnitXML'),
    outputFormatter: Symbol.for('OutputFormatter'),
    configuration: Symbol.for('Configuration'),
    testController: Symbol.for('TestController'),
    outputChannel: Symbol.for('OutputChannel'),
    testCollection: Symbol.for('TestCollection'),
    testRunnerBuilder: Symbol.for('TestRunnerBuilder'),
    testRunHandler: Symbol.for('TestRunHandler'),
    phpUnitLinkProvider: Symbol.for('PHPUnitLinkProvider'),
    testCommandRegistry: Symbol.for('TestCommandRegistry'),
    fileChangedEmitter: Symbol.for('FileChangedEmitter'),
    testFileDiscovery: Symbol.for('TestFileDiscovery'),
    testFileWatcher: Symbol.for('TestFileWatcher'),
    testWatchManager: Symbol.for('TestWatchManager'),
    coverageCollector: Symbol.for('CoverageCollector'),
    testQueueBuilder: Symbol.for('TestQueueBuilder'),
    errorDialogObserver: Symbol.for('ErrorDialogObserver'),
    outputChannelObserver: Symbol.for('OutputChannelObserver'),
};
